version: '3.8'
x-common-variables:
  &environment
  TW_ENV: dev
  SENTRY_DSN: None
  JOB2SKILLS_SERVICE_URL: None
  PORT: 8000
  WEB_CONCURRENCY: 1
  MAX_WORKERS: 1
  TIMEOUT: 600

services:
  web:
    environment: *environment
    image: ai-internal-keyword-extractor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
